#ifndef MQTT_COMMON_H
#define MQTT_COMMON_H

// Topic宏定义
#define MESH_TOPIC_DISCOVER "SIMPLE_MESH/DISCOVER"
#define MESH_TOPIC_LOGIN "SIMPLE_MESH/LOGIN"
#define MESH_TOPIC_CONTROLLER_NOTIFY "SIMPLE_MESH/CONTROLLER_NOTIFY"
#define MESH_TOPIC_AGENT_STATUS "SIMPLE_MESH/AGENT_STATUS"

// 角色类型
typedef enum {
    MODE_UNKNOWN = 0,
    MODE_CONTROLLER,
    MODE_AGENT
} mesh_mode_t;

#endif // MQTT_COMMON_H 