#ifndef MQTT_TOPICS_H
#define MQTT_TOPICS_H

// SimpleMesh MQTT Topic 定义
// 格式: SIMPLE_MESH//<ACTION>
#define MESH_TOPIC_DISCOVER "SIMPLE_MESH/DISCOVER"
#define MESH_TOPIC_LOGIN "SIMPLE_MESH/LOGIN"
#define MESH_TOPIC_CONTROLLER_NOTIFY "SIMPLE_MESH/CONTROLLER_NOTIFY"

// 基础前缀

#endif // MQTT_TOPICS_H 